version: "3.9"
   
services:
  web:
    build: .
    #command: python3 MyPantry/manage.py makemigrations
    command: python3 MyPantry/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"

